max_epochs: 10
accelerator: "gpu"
devices: 1
max_steps: ${max_steps}

enable_checkpointing: false
limit_val_batches: 2 # how many batches to use for validation
val_check_interval: 300 # after how many training steps do we do a validation step