name: omtra
channels:
  - pyg
  - pytorch
  - dglteam/label/th24_cu121
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.13=hb9d3cd8_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.8.0=pyhd8ed1ab_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311h9ecbd09_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hbb29018_2
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - chardet=5.2.0=py311h38be061_2
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311hd18a35c_0
  - cpython=3.11.11=py311hd8ed1ab_1
  - crc32c=2.7.1=py311h9ecbd09_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.55=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.12=py311hfdbb021_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.15=pyhd8ed1ab_1
  - dgl=2.4.0.th24.cu121=py311_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.0=h59595ed_0
  - einops=0.8.0=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h5888daf_0
  - ffmpeg=7.1.0=gpl_he2fd91e_701
  - filelock=3.17.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.4=py311h2dc5d0c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311h0f6cedb_3
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.1.1=py311hfdbb021_1
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=9.0.0=hfac3d4d_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.20.2=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py311h92ebd52_6
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libclang-cpp18.1=18.1.8=default_hf981a13_5
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.0.11=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.9.55=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.80.2=hf974151_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm18=18.1.8=h8b73ec9_2
  - libllvm19=19.1.2=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.45=h943b412_0
  - libpq=16.6=h035377e_1
  - libprotobuf=5.28.2=h5b01275_0
  - librsvg=2.58.0=hce6bd6c_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.48.0=hee588c1_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=h4c95cb1_3
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.11.9=pyhd8ed1ab_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.10.0=py311h38be061_0
  - matplotlib-base=3.10.0=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.0=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py311hd18a35c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.5=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numcodecs=0.15.0=py311h7db5c69_0
  - numpy=1.26.4=py311h64a7726_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311h7db5c69_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.54.0=h4c5309f_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h1322bbf_0
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=6.1.1=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycairo=1.27.0=py311h124c5f0_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.7.2=py311h9053184_4
  - pysocks=1.7.1=pyha55dd90_7
  - pystow=0.5.6=py311h38be061_0
  - python=3.11.11=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytorch=2.4.0=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cluster=1.6.3=py311_torch_2.4.0_cu121
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-lightning=2.5.0.post0=pyh101cb37_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py311_torch_2.4.0_cu121
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - pyzmq=26.2.0=py311h7deb3e3_3
  - qhull=2020.2=h434a139_5
  - qt6-main=6.7.2=h7d13b96_3
  - readline=8.2=h8228510_1
  - referencing=0.36.1=pyhd8ed1ab_0
  - reportlab=4.2.5=py311h9ecbd09_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_1
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.22.3=py311h9e33e62_0
  - scipy=1.15.1=py311hc1ac118_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=75.8.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.37=py311h9ecbd09_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.13.3=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.4.0=py311_cu121
  - torchmetrics=1.6.1=pyhd8ed1ab_0
  - torchtriton=3.0.0=py311
  - torchvision=0.19.0=py311_cu121
  - tornado=6.4.2=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py311h9ecbd09_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - zarr=3.0.1=pyhd8ed1ab_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - biotite==1.2.0
      - biotraj==1.2.2
      - cachetools==5.5.1
      - cloudpathlib==0.20.0
      - dataclasses==0.6
      - docker-pycreds==0.4.0
      - duckdb==1.1.3
      - eval-type-backport==0.2.2
      - frozenlist==1.5.0
      - future==1.0.0
      - gcsfs==2024.12.0
      - gemmi==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.5
      - joblib==1.4.2
      - jupyterlab-widgets==1.1.11
      - line-profiler==4.2.0
      - llvmlite==0.44.0
      - mmcif==0.91.0
      - mols2grid==2.0.0
      - multidict==6.1.0
      - notebook==7.3.2
      - numba==0.61.2
      - oauthlib==3.2.2
      - peppr==0.2.3
      - plinder==0.2.20
      - plotly==5.24.1
      - posebusters==0.5.1
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - py3dmol==2.4.2
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pynndescent==0.5.13
      - rdkit==2024.9.4
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - smmap==5.0.2
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - umap-learn==0.5.7
      - useful-rdkit-utils==0.80
      - wandb==0.19.4
      - widgetsnbextension==3.6.10
      - yarl==1.18.3
prefix: /net/galaxy/home/koes/icd3/.conda/envs/omtra
