denovo_ligand:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
denovo_ligand_extra_feats:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
denovo_ligand_condensed:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
ligand_conformer:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
ligand_conformer_extra_feats:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
ligand_conformer_condensed:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - pb_valid_unconditional:
      train: true
      params:
        max_workers: 0
rigid_docking:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
rigid_docking_condensed:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
flexible_docking:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
expapo_conditioned_ligand_docking:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
predapo_conditioned_ligand_docking:
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - ligand_rmsd:
      train: true
      params:
        rmsd_threshold: 2.0
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
protein_ligand_denovo:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
fixed_protein_ligand_denovo:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
fixed_protein_ligand_denovo_condensed:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
exp_apo_conditioned_denovo_ligand:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
pred_apo_conditioned_denovo_ligand:
  - validity:
      train: true
      params: {}
  - stability:
      train: true
      params: {}
  - reos_and_rings:
      train: true
      params: {}
  - geometry:
      train: true
      params:
        ignore_hydrogens: true
  - flatness:
      train: true
      params:
        threshold_flatness: 0.1
  - intermolecular_distance:
      train: true
      params:
        clash_cutoff: 0.05
  - volume_overlap:
      train: true
      params:
        clash_cutoff: 0.05
  