_target_: omtra.models.omtra.OMTRA

defaults:
  - _self_
  - conditional_paths: default
  - vector_field: default
  - optimizer: default

k_checkpoints: 15
checkpoint_interval: 5000
fake_atom_p: ${fake_atom_p}
