ligand_conformer_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
rigid_docking_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
flexible_docking_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
ligand_conformer_from_pharmacophore_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
rigid_docking_pharmacophore_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True

