# this is where we can set prior distributions for specific modalities of specific tasks
# by default this is actually an empty dictionary; if a prior for a specific task/modalitiy
# is not set here, then a reasonable default will be used. reasonable defaults can be found
# in task class definitions in omtra.tasks.tasks
# so the general format for overriding a 
# task_name:
#   modality_name:
#     type: some_string_name
#     params: {some_param_name: some_param_value, ...}

# note that task_name must be a registered task name (see omtra.tasks.tasks)
# and modality_name must be a registered modality name (see omtra.tasks.modalities)

# below is an example that would override the prior distribution on ligand atom positions for unconditional de novo ligand design
# just uncomment then next two lines for it to take effect
# denovo_ligand:
#   lig_x: {type: gaussian, params: {ot: True}}


expapo_conditioned_ligand_docking:
  prot_atom_x:
    type: apo_exp
    params: {std: 2.5}
predapo_conditioned_ligand_docking:
  prot_atom_x:
    type: apo_pred
    params: {std: 2.5}
exp_apo_conditioned_denovo_ligand:
  prot_atom_x:
    type: apo_exp
    params: {std: 2.5}
pred_apo_conditioned_denovo_ligand:
  prot_atom_x:
    type: apo_pred
    params: {std: 2.5}
protein_ligand_denovo:
  prot_atom_x:
    type: target_dependent_gaussian
    params: {std: 2.5}
flexible_docking:
  prot_atom_x:
    type: target_dependent_gaussian
    params: {std: 2.5}