denovo_ligand_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
fixed_protein_ligand_denovo_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True

protein_ligand_denovo_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True

denovo_ligand_from_pharmacophore_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True

fixed_protein_pharmacophore_ligand_denovo_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True


