ligand_conformer_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
denovo_ligand_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: True
      rigid_body: false
      translation: True
rigid_docking_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True
fixed_protein_ligand_denovo_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: True
      rigid_body: false
      translation: True
flexible_docking_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: False
      translation: True

protein_ligand_denovo_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: True
      rigid_body: false
      translation: True

denovo_ligand_from_pharmacophore_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: True
      rigid_body: false
      translation: True
ligand_conformer_from_pharmacophore_condensed:
  lig_x:
    type: gaussian
    params:
      std: 2.573
      ot: True
      permutation: False

