defaults:
# we just need three things to train on: a model, a trainer and a group of tasks
  - _self_
  - model: default
  - trainer: default
  - task_group: no_protein
  - graph: default

seed: 42

# global overrides
edges_per_batch: 10000 # approx 640 edges/gb ram
num_workers: 2

pharmit_path: ${omtra_root:}/data/pharmit