defaults:
  - _self_
  - model: default
  - trainer: default
  - task_group: protein
  - graph: default
  - prior: default
  - callbacks: default
  - wandb_conf: default

seed: 42

name: i_forgot_to_name_my_run

# global overrides
edges_per_batch: 50000 # TODO: it might be the case the pharmit and plinder tasks support different batch sizes..
num_workers: 2
max_steps: 10000 # number of steps to train for

pharmit_path: ${omtra_root:}/data/pharmit
plinder_path: ${omtra_root:}/data/plinder


# this is a directory that will symlink wandb 
# run names and run ids to the actual hydra output directory
symlink_dir: ./wandb_symlinks


hydra:
  run:
    # make the timestap use milliseconds
    dir: ./outputs/${now:%Y-%m-%d}/${name}_${now:%Y-%m-%d_%H-%M-%f}