defaults:
  - _self_
  - model: default
  - ligand_encoder: none
  - trainer: default
  - task_group: protein
  - graph: default
  - prior: 
    - conformer_indep
    - denovo_permute
  - callbacks: no_checkpoint
  - wandb_conf: default
  - eval: default

mode: omtra # mode for training, can be omtra (train omtra) or ligand_encoder (train just the ligand encoder)

seed: 42

name: i_forgot_to_name_my_run

# global overrides
edges_per_batch: 300000 # TODO: it might be the case the pharmit and plinder tasks support different batch sizes..
num_workers: 2
max_steps: 1000 # number of steps to train for
fake_atom_p: 0.3 # upper bound on fraction of fake atoms added to a molecule
distort_p: 0.2  # upper bound on fraction of atoms distorted
plinder_pskip_factor: 0.0 # 0 -> no weighted sampling, 1 -> uniform sampling over clusters
res_id_embed_dim: 64 # dimension of residue id embedding
pharm_pos_var: 1.2 # st dev to sample noise variance from for pharmocophore positions, 0.0 -> no noise added

pharmit_path: ${omtra_root:}/data/pharmit
plinder_path: ${omtra_root:}/data/plinder
crossdocked_path: ${omtra_root:}/data/crossdocked/internal_split0


# this is a directory that will symlink wandb 
# run names and run ids to the actual hydra output directory
symlink_dir: ./wandb_symlinks

hydra:
  run:
    # make the timestap use milliseconds
    dir: ./outputs/${now:%Y-%m-%d}/${name}_${now:%Y-%m-%d_%H-%M-%f}