defaults:
  # Merge data/pharmit.yaml into cfg.data.pharmit
  - override /data@pharmit: pharmit
  - _self_

tasks:
  task_1:
    datasets:
      # specify multiple dataset references + probabilities
      pharmit:
        probability: 0.7
        batch_size: 32
      some_other:
        probability: 0.3
        batch_size: 16