defaults:
  - _self_
  - model: default
  - trainer: default
  - task_group: no_protein
  - graph: default
  - callbacks: default
  - wandb: disabled

seed: 42

name: development_run

# global overrides
edges_per_batch: 1000 # 12800 # approx 640 edges/gb ram
num_workers: 0

pharmit_path: ${omtra_root:}/data/pharmit