edges:             # parameter for KNN edges
  prot_atom_to_prot_atom:
    type: radius
    params:
      r: 5
  prot_atom_to_lig:
    type: radius
    params:
      r: 8
  lig_to_prot_atom:
    type: knn
    params:
      k: 15
  # prot_res_to_lig:
  #   type: radius
  #   params:
  #     r: 8
  # lig_to_prot_res:
  #   type: knn
  #   params:
  #     k: 3
  prot_atom_to_npnde:
    type: radius
    params:
      r: 8
  npnde_to_prot_atom:
    type: knn
    params:
      k: 5
  # prot_res_to_npnde:
  #   type: radius
  #   params:
  #     r: 8
  # npnde_to_prot_res:
  #   type: knn
  #   params:
  #     k: 3
  prot_atom_to_pharm:
    type: radius
    params:
      r: 8
  pharm_to_prot_atom:
    type: knn
    params:
      k: 5
  # prot_res_to_pharm:
  #   type: radius
  #   params:
  #     r: 8
  # pharm_to_prot_res:
  #   type: knn
  #   params:
  #     k: 3
  

# enforce certain edge types are symmetric
symmetric_etypes:


cov_prot_edges: true