edges:             # parameter for KNN edges
  pharm_to_pharm:
    type: complete
  lig_to_pharm:
    type: knn
    params:
      k: 5
  npnde_to_pharm:
    type: knn
    params:
      k: 3
  pharm_to_prot_atom:
    type: radius
    params:
      k: 6
  

# enforce certain edge types are symmetric
symmetric_etypes:
  - lig_to_pharm      
  - npnde_to_pharm     
  - pharm_to_prot_atom


cov_prot_edges: true