_target_: omtra.models.vector_field.VectorField


n_vec_channels:                32
n_cp_feats:                    8
n_hidden_scalars:              256
n_hidden_edge_feats:           128
n_recycles:                    1
n_molecule_updates:            4
convs_per_update:              2
n_message_gvps:                3
n_update_gvps:                 3
n_expansion_gvps:              3
separate_mol_updaters:         true
message_norm:                  100
rbf_dmax:                      10
rbf_dim:                       32
time_embedding_dim:            64
token_dim:                     64
attention:                     false
att_type:                      "crosstype"
n_heads:                       1
s_message_dim:                 null
v_message_dim:                 null
dropout:                       0.0
has_mask:                      true
self_conditioning:             true
use_dst_feats:                 false
dst_feat_msg_reduction_factor: 4
rebuild_edges:                 true
res_id_embed_dim:              64
learnable_vec_norm:            false