_target_: omtra.models.vector_field.VectorField


n_vec_channels:                32
n_cp_feats:                    8
n_hidden_scalars:              256
n_hidden_edge_feats:           36
rbf_dmax:                      10
rbf_dim:                       32
time_embedding_dim:            64
token_dim:                     64
n_heads:                       8
dropout:                       0.1
has_mask:                      true
self_conditioning:             true
res_id_embed_dim:              64
pos_emb:                       true
n_pre_gvp_convs:               1