processed_data_dir: ${plinder_path}
pskip_factor: ${plinder_pskip_factor} # 0 -> no weighted sampling, 1 -> uniform sampling over clusters
res_id_embed_dim: ${res_id_embed_dim} # dimension of residue id embedding
max_pharms_sampled: ${max_pharms_sampled}
pharm_idxs: ${pharm_idxs}
# graphs_per_chunk: 1000
