# This could be a task group where all the tasks are listed
defaults:
  - _self_

  # Load the multitask data config from configs/task_group/data/multitask.yaml
  - data: multitask
  # Merge pharmit.yaml directly into the single_dataset_configs dict (which is used for MultiTaskDataModule)
  - data@data.multitask_dataset_config.single_dataset_configs.pharmit: pharmit

tasks:
  - name: "LigandConformer"
    probability: 0.2
  - name: "ProteinPharmacophore"
    probability: 0.3
  - name: "UnconditionalLigandDocking"
    probability: 0.3
  - name: "ApoConditionedLigandDocking"
    probability: 0.2

dataset_task_coupling:
  LigandConformer:
    - [pharmit, 1.0]
  ProteinPharmacophore:
    - [pharmit, 1.0]
  unconditional_ligand_docking:
    - [pharmit, 1.0]
  apo_conditioned_denovo_ligand:
    - [pharmit, 1.0]