# this block must be included in all task_group configs
# especially the datamodule: default attribue
defaults:
  - _self_
  - datamodule: default


# Define tasks with time-varying probabilities
# this is p(task) but p(task) can change through the course of training
task_phases:
  - duration_batches: null
    tasks:
      - name: rigid_docking
        probability: 0.5
      - name: fixed_protein_ligand_denovo
        probability: 0.5

# define p(dataset|task) coupling (assume static for simplicity)
dataset_task_coupling:
  rigid_docking:
    - [crossdocked, 1.0]
  fixed_protein_ligand_denovo:
    - [crossdocked, 1.0]