# this block must be included in all task_group configs
# especially the datamodule: default attribue
defaults:
  - _self_
  - datamodule: default


# Define tasks with time-varying probabilities
# this is p(task) but p(task) can change through the course of training
task_phases:
  - duration_batches: null
    tasks:
      - name: flexible_docking_extra_feats
        probability: 0.5
      - name: protein_ligand_denovo_extra_feats
        probability: 0.5

# define p(dataset|task) coupling (assume static for simplicity)
dataset_task_coupling:
  flexible_docking_extra_feats:
    - [plinder, 1.0]
  protein_ligand_denovo_extra_feats:
    - [plinder, 1.0]