# this block must be included in all task_group configs
# especially the datamodule: default attribue
defaults:
  - _self_
  - datamodule: default


# Define tasks with time-varying probabilities
# this is p(task) but p(task) can change through the course of training
task_phases:
  - duration_batches: null
    tasks:
      - name: expapo_conditioned_ligand_docking_condensed
        probability: 0.125
      - name: predapo_conditioned_ligand_docking_condensed
        probability: 0.125
      - name: exp_apo_conditioned_denovo_ligand_condensed
        probability: 0.125
      - name: pred_apo_conditioned_denovo_ligand_condensed
        probability: 0.125
      - name: protein_ligand_denovo_condensed
        probability: 0.125
      - name: flexible_docking_condensed
        probability: 0.125
      - name: denovo_ligand_condensed
        probability: 0.125
      - name: ligand_conformer_condensed
        probability: 0.125

# define p(dataset|task) coupling (assume static for simplicity)
dataset_task_coupling:
  expapo_conditioned_ligand_docking_condensed:
    - [plinder, 1.0]
  predapo_conditioned_ligand_docking_condensed:
    - [plinder, 1.0]
  exp_apo_conditioned_denovo_ligand_condensed:
    - [plinder, 1.0]
  pred_apo_conditioned_denovo_ligand_condensed:
    - [plinder, 1.0]
  protein_ligand_denovo:
    - [plinder, 1.0]
  flexible_docking_condensed:
    - [plinder, 1.0]
  denovo_ligand_condensed:
    - [pharmit, 1.0]
  ligand_conformer_condensed:
    - [pharmit, 1.0]