# this block must be included in all task_group configs
# especially the datamodule: default attribue
defaults:
  - _self_
  - datamodule: default


# Define tasks with time-varying probabilities
# this is p(task) but p(task) can change through the course of training
task_phases:
  - duration_batches: null  # remaining batches (no upper limit)
    tasks:
      - name: denovo_ligand_extra_feats
        probability: 0.999
      - name: ligand_conformer_extra_feats
        probability: 0.0001

# define p(dataset|task) coupling (assume static for simplicity)
dataset_task_coupling:
  denovo_ligand_extra_feats:
    - [pharmit, 1.0]
  ligand_conformer_extra_feats:
    - [pharmit, 1.0]