# this block must be included in all task_group configs
# especially the datamodule: default attribue
defaults:
  - _self_
  - datamodule: default


# Define tasks with time-varying probabilities
# this is p(task) but p(task) can change through the course of training
task_phases:
  - duration_batches: 300000
    tasks:
      - name: denovo_ligand_condensed
        probability: 0.5
      - name: ligand_conformer_condensed
        probability: 0.5
  - duration_batches: null
    tasks:
      - name: rigid_docking_condensed
        probability: 0.25
      - name: fixed_protein_ligand_denovo_condensed
        probability: 0.25
      - name: flexible_docking_condensed
        probability: 0.25
      - name: protein_ligand_denovo_condensed
        probability: 0.25

# define p(dataset|task) coupling (assume static for simplicity)
dataset_task_coupling:
  denovo_ligand_condensed:
    - [pharmit, 1.0]
  ligand_conformer_condensed:
    - [pharmit, 1.0]
  rigid_docking_condensed:
    - [plinder, 1.0]
  fixed_protein_ligand_denovo_condensed:
    - [plinder, 1.0]
  flexible_docking_condensed:
    - [plinder, 1.0]
  protein_ligand_denovo_condensed:
    - [plinder, 1.0]